GAME_CANVAS_WIDTH = 400
GAME_CANVAS_HEIGHT = 400

PLAYER_LENGTH = 20
PLAYER_HEIGHT = 10
PLAYER_START_Y_OFFSET = 20
PLAYER_START_X = GAME_CANVAS_WIDTH / 2
PLAYER_START_Y = GAME_CANVAS_HEIGHT - (PLAYER_START_Y_OFFSET + PLAYER_HEIGHT)
PLAYER_COLOR = "white"

BOT_LENGTH = 20
BOT_HEIGHT = 10
BOT_START_X = GAME_CANVAS_WIDTH / 2
BOT_START_Y = 20
BOT_COLOR = "white"

BALL_LENGTH = 5
BALL_HEIGHT = 10
BALL_START_X = GAME_CANVAS_WIDTH / 2
BALL_START_Y = GAME_CANVAS_HEIGHT / 2
BALL_COLOR = "white"