name: SBOM generation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate SBOM
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        $RUNNER_TEMP/sbom-tool generate -b ${{ github.workspace }}/SBOM -bc ${{ github.workspace }}/ -pn Test -pv 1.0.0 -ps 309SWEG -nsb https://sbom.mycompany.com -V Verbose
        ls -a ${{github.workspace}}
