name: SBOM generation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate SBOM
        run: |
          mkdir sbom_location
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b ./sbom_location -bc ${{ github.workspace }} -pn Test -pv 1.0.0 -ps 309SWEG -nsb https://sbom.mycompany.com
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: SBOM_Download
          path: sbom_location/
      
